<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  
  <modelVersion>4.0.0</modelVersion>
  <groupId>me.JordanG8</groupId>
  <artifactId>Obsidian-Armor</artifactId>
  <version>1.0.0</version>
  
  <properties>
  	<maven.compiler.source>21</maven.compiler.source>
  	<maven.compiler.target>21</maven.compiler.target>
  	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  
  <repositories>
        <repository>
            <id>minecraft-libraries</id>
            <url>https://libraries.minecraft.net</url>
        </repository>

        <repository>
            <id>drakescraft-labs-maven</id>
            <url>https://drakescraft-labs.github.io/maven-repo/</url>
        </repository>

  	<repository>
  		<id>paper-repo</id>
  		<url>https://repo.papermc.io/repository/maven-public/</url>
  	</repository>
  	
  	<repository>
  		<id>spigot-repo</id>
  		<url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
  	</repository>
  	
  	<repository>
  		<id>jitpack.io</id>
  		<url>https://jitpack.io</url>
  	</repository>
  </repositories>
  
  <build>
  	<finalName>${project.name} v${project.version}</finalName>
  	<defaultGoal>clean package</defaultGoal>
  	<sourceDirectory>${basedir}/src/main/java</sourceDirectory>
  	
  	<resources>
  		<resource>
  			<directory>${basedir}/src/main/resources</directory>
  			<filtering>true</filtering>
  			<includes>
  				<include>*</include>
  			</includes>
  		</resource>
  	</resources>
  </build>
  
  <dependencies>
  	<dependency>
  		<groupId>io.papermc.paper</groupId>
  		<artifactId>paper-api</artifactId>
            <version>1.21.11-R0.1-SNAPSHOT</version>
  		<scope>provided</scope>
  	</dependency>
  	
  	<dependency>
  		<groupId>com.github.TheBusyBiscuit</groupId>
  		<artifactId>CS-CoreLib</artifactId>
  		<version>8081bb4fe4</version>
  		<scope>provided</scope>
  		<exclusions>
  			<exclusion>
  				<groupId>io.github.thebusybiscuit</groupId>
  				<artifactId>cscorelib2</artifactId>
  			</exclusion>
  			<exclusion>
  				<groupId>org.bstats</groupId>
  				<artifactId>bstats-bukkit</artifactId>
  			</exclusion>
  		</exclusions>
  	</dependency>
  	
  	<dependency>
            <groupId>com.github.drakescraft_labs</groupId>
            <artifactId>slimefun-core</artifactId>
            <version>11.0-Drake-1.21.11-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
  </dependencies>
</project>
